site_name: Everything About 3DC
docs_dir: docs/
# repo_name: '3DCdsc/About'
# repo_url: 'https://github.com/3DCdsc/About'
nav:
    - Home: 
        - Home: 'index.md'
    - Projects: 
        - Projects: 'project.md'
    - Workshops: 
        - Upcoming Workshops: 'Workshops/upcoming_workshops.md'
        - Past Workshops: 'Workshops/past_workshops.md'
        - Workshop Organiser Guide: 'Workshops/workshop_guide.md'
    - Recess Week Challenge:
        - Challenge Introduction: 'recess_week_challenge.md'
        - Cloud-based Lab: 'Recess_Week_Challenge_Stuff/cloud_based_lab.md'
        - HackerRank Guide: 'Recess_Week_Challenge_Stuff/guide.md'
        - Teaser Hints: 'Recess_Week_Challenge_Stuff/teaser_hints.md'
        - Teaser Solution: 'Recess_Week_Challenge_Stuff/teaser_sols.md'
        - Q1 Hints: 'Recess_Week_Challenge_Stuff/q1_hints.md'
        - Q1 Solution: 'Recess_Week_Challenge_Stuff/q1_sol.md'
        - Q2 Solution: 'Recess_Week_Challenge_Stuff/q2_sol.md'
        - Q3 Hints: 'Recess_Week_Challenge_Stuff/q3_hints.md'
        - Q3 Solution: 'Recess_Week_Challenge_Stuff/q3_sol.md'
        - Q4 Solution: 'Recess_Week_Challenge_Stuff/q4_sol.md'
        - Q5 Hints: 'Recess_Week_Challenge_Stuff/q5_hints.md'
    - Join Us:
        - 3DC Membership: '3DC_Membership.md'
        - Join 3DC Core Team: 'Join_3DC_Core.md'
markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true
theme:
    name: material
    favicon: imgs/code.svg
    icon: 
        logo: fontawesome/solid/code
    features:
      - navigation.tabs
    palette:
        scheme: slate
        primary: teal
        accent: indigo
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
