site_name: Everything About 3DC
docs_dir: docs/
repo_name: '3DCdsc/About'
repo_url: 'https://github.com/3DCdsc/About'
markdown_extensions:
    - toc:
        permalink: "#"
theme:
    name: material
    palette:
        scheme: slate
        primary: teal
        accent: indigo
